#pragma once

#define	COLOR_RED 0xff0000
#define COLOR_GREEN 0x00ff00
#define COLOR_LIGHTBLUE 0x0088ff
#define COLOR_BLUE 0x0000ff
#define COLOR_YELLOW 0xffff00
#define COLOR_PURPLE 0xff00ff
#define COLOR_LIGHTGRAY 0xd3d3d3
#define COLOR_WHITE 0xffffff
#define COLOR_BLACK 0x000000

const int color[] = {
	COLOR_RED,COLOR_GREEN,COLOR_LIGHTBLUE,COLOR_BLUE,COLOR_YELLOW,COLOR_PURPLE,COLOR_LIGHTGRAY,COLOR_WHITE,
	COLOR_BLACK
};

enum {
	RED,GREEN,LIGHTBLUE,BLUE,YELLOW,PURPLE,LIGHTGRAY,WHITE,BLACK
};